(add-to-list 'load-path "~/emacspy")
(load "~/emacspy/emacspy")
(exec-python "import emacspy")
(exec-python "emacspy.f.message('foo')")
(exec-python "emacspy.v.foo = emacspy.v.nil")
(eval-python "emacspy.v.foo")
;(eval-python "1/0")
(print "foo")
(print (eval-python "emacspy.v.tab_width"))
(print (eval-python "emacspy.f['+'](1, 2)"))
(print (eval-python "emacspy.f['+'](1, 2).int() + 1"))
